{{- if .Values.ingress.enabled -}}
{{- $fullName := include "black.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "black.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    {{- range .Values.ingress.hosts }}
    - match: Host(`{{ .host | quote }}`) 
      kind: Rule
      services:
        - name: {{ $fullName }}
          port: {{ $svcPort }}
    {{- end }}
  {{- end }}
