{{- if .Values.ingressroute.enabled -}}

{{- $fullName := include "black.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- $host := .Values.ingressroute.host -}}

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "black.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host({{ $host | quote }}) 
      kind: Rule
      services:
        - name: {{ include "black.fullname" . }}
          port: 80
{{- end }}
