apiVersion: k3d.io/v1alpha2
kind: Simple
name: blackred-registry
# servers: 1
# agents: 1
# ports:
#   - port: 8080:80
#     nodeFilters:
#       - loadbalancer
registries:
  create: true
  config: |
    mirrors:
      k3d-blackred-registry:
        endpoint:
          - http://k3d-blackred-registry:5111
