apiVersion: k3d.io/v1alpha2
kind: Simple
name: blackred-demo
servers: 1
agents: 2
kubeAPI:
# host: "myhost.my.domain" # important for the `server` setting in the kubeconfig
  hostIP: "0.0.0.0"
  hostPort: "6550" # Kubernetes API via localhost:6443
image: rancher/k3s:latest
# volumes:
#   - volume: /tmp:/tmp/somepath
#     nodeFilters:
#       - all
ports:
  - port: 443:443 # http via localhost:443
    nodeFilters:
      - loadbalancer
  - port: 8080:8080 # http via localhost:8080
    nodeFilters:
      - loadbalancer
  - port: 80:80 # http via localhost:8080
    nodeFilters:
      - loadbalancer
# env:
#   - envVar: bar=baz
#     nodeFilters:
#       - all
labels:
  - label: node-role.kubernetes.io/worker=true
    nodeFilters:
      - agent[0]
  # - label: foo=bar
  #   nodeFilters:
  #     - server[0]
  #     - loadbalancer
options:
  k3d:
    wait: true
    timeout: "360s"
    # disableLoadbalancer: true
    disableImageVolume: false
  k3s:
    extraServerArgs:
      - --tls-san=127.0.0.1
      # - --disable=servicelb
      - --disable=traefik
    extraAgentArgs: []
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
registries:
  # create: true
  config: |
    mirrors:
      k3d-blackred-registry:
        endpoint:
          - http://k3d-blackred-registry:5111
